# Generated by Django 4.1.7 on 2023-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('reg_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(max_length=100)),
                ('on_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
